#!/usr/bin/env bash

# Check if no arguments are provided
if [ "$#" -eq 0 ]; then
    # Display usage instructions if no IP address is provided
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
    # If an IP address is provided as an argument, execute ping command
    ping -c 5 "$1"
fi
